(function(root){'use strict';
 const levels=['Easy','Medium','Hard','Expert'],MAX_BYTES=10*1024*1024;
 const fail=()=>{throw Error('This file contains invalid or unsupported profile data.')};
 const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
 const num=v=>typeof v==='number'&&Number.isFinite(v);
 const digit=v=>Number.isInteger(v)&&v>=0&&v<=9;
 function safe(v){if(!v||typeof v!=='object')return;for(const k of Object.keys(v)){if(['__proto__','constructor','prototype'].includes(k))fail();safe(v[k])}}
 function ink(v){if(!Array.isArray(v)||v.length>2000)fail();for(const s of v){if(!Array.isArray(s)||s.length>10000)fail();for(const p of s)if(!Array.isArray(p)||p.length!==2||p.some(n=>!num(n)||Math.abs(n)>100))fail()}return v}
 function solution(g){if(!Array.isArray(g)||g.length!==81||g.some(v=>!digit(v)||!v))fail();for(let u=0;u<9;u++){const row=[],col=[],box=[];for(let k=0;k<9;k++){row.push(g[u*9+k]);col.push(g[k*9+u]);box.push(g[(Math.floor(u/3)*3+Math.floor(k/3))*9+u%3*3+k%3])}if([row,col,box].some(a=>new Set(a).size!==9))fail()}}
 function game(g,level){if(!obj(g)||g.level!==level)fail();solution(g.solution);if(!Array.isArray(g.puzzle)||g.puzzle.length!==81||g.puzzle.some((v,i)=>!digit(v)||(v&&v!==g.solution[i])))fail();if(!Array.isArray(g.cells)||g.cells.length!==81||!num(g.elapsed)||g.elapsed<0||typeof g.complete!=='boolean')fail();const cells=g.cells.map(c=>{if(!obj(c)||!digit(c.value)||!obj(c.notes))fail();const notes={};for(const [d,s]of Object.entries(c.notes)){if(!/^[1-9]$/.test(d))fail();notes[d]=ink(s)}let pending=null;if(c.pending!=null){if(!obj(c.pending)||!digit(c.pending.digit)||c.value)fail();pending={digit:c.pending.digit,strokes:ink(c.pending.strokes)};if(c.pending.notes!==undefined){if(typeof c.pending.notes!=='boolean')fail();pending.notes=c.pending.notes}}if(typeof c.error!=='boolean')fail();return {value:c.value,ink:ink(c.ink),notes,pending,error:c.error}});if(g.complete&&cells.some((c,i)=>!g.puzzle[i]&&(c.value!==g.solution[i]||c.pending)))fail();const out={v:typeof g.v==='string'?g.v:'0.9.8',level,puzzle:g.puzzle,solution:g.solution,cells,elapsed:g.elapsed,started:Date.now(),complete:g.complete,userPaused:!!g.userPaused,score:num(g.score)?g.score:0};if(g.rating!==undefined){if(!obj(g.rating)||typeof g.rating.technique!=='string'||g.rating.technique.length>300||!levels.includes(g.rating.level))fail();out.rating=g.rating}return out}
 function profile(p){if(!obj(p)||typeof p.name!=='string'||!p.name.trim()||p.name.length>100||!obj(p.prefs)||!obj(p.games)||!obj(p.learn)||!Array.isArray(p.stats)||p.stats.length>100000)fail();const prefs={};for(const k of ['level','check','recognitionMode']){const allowed={level:levels,check:['off','conflict','solution'],recognitionMode:['confirm','auto','leave']}[k];if(p.prefs[k]!==undefined){if(!allowed.includes(p.prefs[k]))fail();prefs[k]=p.prefs[k]}}for(const k of ['notes','matching','cellChangeWriting'])if(p.prefs[k]!==undefined){if(typeof p.prefs[k]!=='boolean')fail();prefs[k]=p.prefs[k]}const games={};for(const [level,g]of Object.entries(p.games)){if(!levels.includes(level))fail();games[level]=game(g,level)}const learn={};for(const [d,samples]of Object.entries(p.learn)){if(!/^[1-9]$/.test(d)||!Array.isArray(samples)||samples.length>12)fail();for(const a of samples)if(!Array.isArray(a)||a.length!==784||a.some(n=>!num(n)||n<0||n>1))fail();learn[d]=samples}const stats=p.stats.map(s=>{if(!obj(s)||!levels.includes(s.level)||!num(s.time)||s.time<0||typeof s.date!=='string'||!Number.isFinite(Date.parse(s.date)))fail();return {level:s.level,time:s.time,date:s.date}});return {name:p.name.trim(),prefs,games,learn,stats}}
 function parse(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>MAX_BYTES)throw Error('Choose a Sudoku Pencil backup smaller than 10 MB.');let data;try{data=JSON.parse(text)}catch{throw Error('This is not a readable JSON backup file.')}safe(data);if(!obj(data)||data.format!=='sudoku-pencil-backup')throw Error('Choose a Sudoku Pencil backup file.');if(data.schemaVersion!==1)throw Error('This backup version is not supported. Update Sudoku Pencil before restoring it.');if(!Array.isArray(data.profiles)||!data.profiles.length||data.profiles.length>100)fail();return {createdAt:typeof data.createdAt==='string'?data.createdAt:'',profiles:data.profiles.map(profile)}}
 function exportText(profiles,version){const data={format:'sudoku-pencil-backup',schemaVersion:1,appVersion:version,createdAt:new Date().toISOString(),profiles};const text=JSON.stringify(data,null,2);parse(text);return text}
 function merge(db,profiles){const next=JSON.parse(JSON.stringify(db)),names=new Set(Object.values(next.profiles).map(p=>p.name));for(const p of profiles){let name=p.name,n=1;while(names.has(name))name=`${p.name} (restored${n++>1?' '+(n-1):''})`;names.add(name);let id;do{id='restored-'+crypto.randomUUID()}while(next.profiles[id]);next.profiles[id]={...p,name}}return next}
 const api={parse,exportText,merge,MAX_BYTES};if(typeof module!=='undefined')module.exports=api;else root.SudokuBackup=api;
})(globalThis);
