/* Screenshot import and editable preview. No server or account is required. */
(function(root){'use strict';
function create(hooks){
 const $=id=>document.getElementById(id),dialog=$('importDialog'),source=document.createElement('canvas');
 let session=null,imageReady=false,points=[],serial=0,worker=null;
 const fields=[];
 function invalidate(){serial++;if(worker){worker.terminate();worker=null}$('importReviewed').checked=false;$('importPlay').disabled=true}
 function changed(){invalidate();$('importMessage').textContent='Check every given against your screenshot, then tick the review box.'}
 function rect(){if(points.length!==2)return null;return {x:Math.min(points[0].x,points[1].x),y:Math.min(points[0].y,points[1].y),w:Math.abs(points[1].x-points[0].x),h:Math.abs(points[1].y-points[0].y)}}
 function draw(){const c=$('importImage'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(!imageReady)return;x.drawImage(source,0,0);const r=rect();if(r){x.fillStyle='#426b6125';x.fillRect(r.x,r.y,r.w,r.h);x.strokeStyle='#166952';x.lineWidth=Math.max(2,c.width/250);x.strokeRect(r.x,r.y,r.w,r.h)}for(const p of points){x.fillStyle='#b33c30';x.beginPath();x.arc(p.x,p.y,Math.max(5,c.width/100),0,Math.PI*2);x.fill()}}
 function setGrid(digits,uncertain=[]){for(let i=0;i<81;i++){fields[i].value=digits[i]||'';fields[i].classList.toggle('uncertain',uncertain.includes(i))}changed()}
 function list(){const host=$('importLibrary');host.replaceChildren();const items=hooks.list().sort((a,b)=>b.challengeDate.localeCompare(a.challengeDate));$('importLibraryEmpty').hidden=!!items.length;host.closest('details').open=!!items.length;for(const g of items){const b=document.createElement('button');b.type='button';b.textContent=`${g.challengeDate} · ${g.title} · ${g.sourceDifficulty}${g.complete?' · Completed':' · Resume'}`;b.onclick=()=>{if(!session)return;try{hooks.load(g.importId);close(false)}catch(e){$('importMessage').textContent=e.message}};host.append(b)}}
 function open(){if(session)return;session=hooks.pause();invalidate();imageReady=false;points=[];$('importFile').value='';$('importImage').hidden=true;$('importRead').disabled=true;$('importWhole').disabled=true;$('importCropReset').disabled=true;$('importTitle').value='NYT daily puzzle';const d=new Date();$('importDate').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;$('importDifficulty').value='Unknown';setGrid(Array(81).fill(0));$('importMessage').textContent='Choose a screenshot of an unplayed puzzle. You can also enter its givens in the preview.';$('importCropHelp').textContent='Tap the top-left outer corner of the puzzle, then its bottom-right outer corner.';list();dialog.showModal()}
 function close(restore=true){if(!session)return;const previous=session;session=null;invalidate();dialog.close();source.width=source.height=1;$('importImage').width=$('importImage').height=1;imageReady=false;if(restore)hooks.resume(previous)}
 async function fileChanged(){invalidate();imageReady=false;points=[];$('importImage').hidden=true;$('importRead').disabled=true;$('importWhole').disabled=true;$('importCropReset').disabled=true;const file=$('importFile').files[0];if(!file)return;const ticket=serial;let url;
 try{if(file.size>12*1024*1024)throw Error('Choose a screenshot smaller than 12 MB.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG or WebP screenshot.');$('importMessage').textContent='Opening screenshot…';url=URL.createObjectURL(file);const image=new Image();image.src=url;await image.decode();if(ticket!==serial||!session)return;if(image.width*image.height>24000000)throw Error('This image is too large. Crop it to the puzzle in Photos first.');const scale=Math.min(1,1400/Math.max(image.width,image.height));source.width=Math.round(image.width*scale);source.height=Math.round(image.height*scale);const x=source.getContext('2d');x.fillStyle='white';x.fillRect(0,0,source.width,source.height);x.drawImage(image,0,0,source.width,source.height);const c=$('importImage');c.width=source.width;c.height=source.height;imageReady=true;c.hidden=false;$('importWhole').disabled=false;$('importCropReset').disabled=false;draw();$('importCropHelp').textContent='Tap the top-left outer corner of the puzzle, then its bottom-right outer corner.';$('importMessage').textContent='Mark the puzzle corners on your screenshot. Reading a new image will replace this preview.'}catch(e){if(ticket===serial&&session)$('importMessage').textContent=e.message}finally{if(url)URL.revokeObjectURL(url)}}
 function cropChanged(){invalidate();const r=rect();$('importRead').disabled=!r||r.w<90||r.h<90;draw();$('importCropHelp').textContent=points.length===1?'Now tap the bottom-right outer corner.':points.length===2?'Check that the green rectangle follows all four outer edges. Then tap Read digits.':'Tap the top-left outer corner of the puzzle, then its bottom-right outer corner.'}
 async function read(){const r=rect();if(!r||!session)return;invalidate();const ticket=serial;$('importRead').disabled=true;$('importMessage').textContent='Reading printed digits…';await new Promise(resolve=>setTimeout(resolve,30));try{if(ticket!==serial||!session)return;const result=SudokuScreenshot.read(source,r);setGrid(result.digits,result.uncertain);$('importMessage').textContent=`Read ${result.digits.filter(Boolean).length} givens. ${result.uncertain.length} uncertain cells are marked in amber. Compare every cell, including blanks, with the screenshot.`}catch(e){$('importMessage').textContent='Could not read this crop. Mark the corners again or enter the givens manually.'}finally{if(session)$('importRead').disabled=false}}
 async function play(){if(!session||!$('importReviewed').checked)return;const puzzle=fields.map(f=>Number(f.value)||0),title=$('importTitle').value.trim(),date=$('importDate').value,difficulty=$('importDifficulty').value;
 if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)){$('importMessage').textContent='Add a puzzle name and a date first.';return}
 const ticket=++serial;$('importPlay').disabled=true;$('importMessage').textContent='Checking that this puzzle has exactly one solution…';
 try{const solution=await new Promise((resolve,reject)=>{worker=new Worker('./import-worker.js');const active=worker;const timeout=setTimeout(()=>{active.terminate();if(worker===active)worker=null;reject(Error('This puzzle took too long to check. Review the givens and try again.'))},15000);active.onmessage=e=>{clearTimeout(timeout);active.terminate();if(worker===active)worker=null;e.data.error?reject(Error(e.data.error)):resolve(e.data.solution)};active.onerror=()=>{clearTimeout(timeout);active.terminate();if(worker===active)worker=null;reject(Error('The puzzle checker could not load. Refresh online and try again.'))};active.postMessage(puzzle)});if(ticket!==serial||!session)return;hooks.start({puzzle,solution,title,challengeDate:date,sourceDifficulty:difficulty});close(false)}catch(e){if(ticket===serial&&session){$('importMessage').textContent=e.message;$('importPlay').disabled=false}}}
 for(let i=0;i<81;i++){const f=document.createElement('input');f.type='text';f.inputMode='numeric';f.maxLength=1;f.autocomplete='off';f.setAttribute('aria-label',`Import row ${Math.floor(i/9)+1} column ${i%9+1}`);f.oninput=()=>{f.value=f.value.replace(/[^1-9]/g,'').slice(-1);f.classList.remove('uncertain');changed()};fields.push(f);$('importGrid').append(f)}
 $('importImage').onclick=e=>{if(!imageReady)return;const c=$('importImage'),r=c.getBoundingClientRect();if(points.length===2)points=[];points.push({x:Math.max(0,Math.min(c.width,(e.clientX-r.left)*c.width/r.width)),y:Math.max(0,Math.min(c.height,(e.clientY-r.top)*c.height/r.height))});cropChanged()};
 $('importWhole').onclick=()=>{if(imageReady){points=[{x:0,y:0},{x:source.width,y:source.height}];cropChanged()}};
 $('importCropReset').onclick=()=>{points=[];cropChanged()};$('importRead').onclick=read;$('importFile').onchange=fileChanged;$('importPlay').onclick=play;$('importClose').onclick=()=>close();$('importReviewed').onchange=()=>{serial++;if(worker){worker.terminate();worker=null}$('importPlay').disabled=!$('importReviewed').checked};
 for(const id of ['importTitle','importDate','importDifficulty'])$(id).oninput=changed;
 dialog.addEventListener('cancel',e=>{e.preventDefault();close()});return {open,isOpen:()=>!!session};
}
root.SudokuImports={create};
})(globalThis);
